version: "3.9"

services:
  shareit-db:
    image: postgres:16
    container_name: shareit-db
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5433:5432"
    volumes:
      - shareit_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  shareit_data: